### PR TITLE
Add Hazard 2.5 rev2043

### PR DESCRIPTION
**Pull request by Fulgen301**

### CODE REVIEW

**Comment by Somebodyisnobody** [comment]
For the record: We interpret [the content-license](https://github.com/legacyclonk/content/blob/39bd1107a5f9510006bdc89ed139a3af1d82c076/clonk_content_license.txt) to apply to the original Clonk Rage content files only. The CC-BY license of the Hazard pack is also compatible for non-commercial use, as it is the case for LegacyClonk. Thus, the contents of the Hazard Pack are made available under the same license (CC-BY 4.0), while the original files of RedWolf Design remain under CC-BY-NC 4.0.

**Comment by Somebodyisnobody** [comment]
Currently every pack has a `COPYING`-file.
I want suggest to use the first line always for the license title. This is currently done in Hazard.c4d and Hazard.c4f only:
https://github.com/legacyclonk/content/blob/2aa63db0cbd9e9cd94b241f72449af78591a6a90/Hazard.c4d/COPYING#L1-L4
https://github.com/legacyclonk/content/blob/2aa63db0cbd9e9cd94b241f72449af78591a6a90/Fantasy.c4d/COPYING#L1-L6

Should a parsing of the license be necessary in the future, e.g. because a feature in the game or a later editor requires it, the later the effort is more manageable if a clean system is started now. Probably Hazard was not the last pack to be added.

----
Furthermore, I would like to suggest that the RedWolf Design packs to which the [Clonk Content License](https://github.com/legacyclonk/content/blob/2aa63db0cbd9e9cd94b241f72449af78591a6a90/clonk_content_license.txt) applies are listed individually in it.
[clonk_content_license.txt.diff.txt](https://github.com/legacyclonk/content/files/7908909/clonk_content_license.txt.diff.txt)

<details>
<summary>Modified clonk_content_license.txt</summary>

```
Clonk game content made by RedWolf Design is available under the following license:

Creative Commons Attribution-NonCommercial (CC BY-NC)
http://creativecommons.org/licenses/by-nc/4.0/

This applies to graphics, audio data, scripting, and text found in the
game release packages of RedWolf Design (usually packed inside c4f, c4g, and c4d group files).

You are free to:
    Share — copy and redistribute the material in any medium or format
    Adapt — remix, transform, and build upon the material

Under the following terms:
    Attribution — You must give appropriate credit, provide a link to the
    license, and indicate if changes were made. You may do so in any reasonable
    manner, but not in any way that suggests the licensor endorses you or your use.
    NonCommercial — You may not use the material for commercial purposes.

The license above is applicable to game content created by RedWolf Design. The following
RedWolf Design game content is used in this repository for LegacyClonk:
    - Fantasy.c4d
    - Fantasy.c4f
    - FarWorlds.c4d
    - FarWorlds.c4f
    - Knights.c4d
    - Knights.c4f
    - Material.c4g
    - Melees.c4f
    - Missions.c4f
    - Music.c4g
    - Objects.c4d
    - Races.c4f
    - Sound.c4g
    - Tutorial.c4f
    - Western.c4d
    - Western.c4f
    - Worlds.c4f 
```
</details>

**Comment by Fulgen301** [comment]
While I agree that the way COPYING is used can be simplified, this is beyond the scope of this PR, which is about adding Hazard to the repository,

**Comment by Somebodyisnobody** [comment]
This is okay for me, but the issue should be resolved until the next release

**Pull request merged**
